import type { ActivityStats, StaleFile } from './commands/onboarding'
import type { FileChurnStats } from './scoring'
import Table from 'cli-table3'
import pc from 'picocolors'
import { formatRelative } from './format'

export function renderChurn(
  path: string,
  stats: FileChurnStats[],
): string {
  const out: string[] = []

  out.push('')
  out.push(
    pc.bold(` Churn analysis for ${pc.cyan(path)}`)
    + pc.dim(` (${stats.length} file${stats.length !== 1 ? 's' : ''})`),
  )
  out.push('')

  const table = new Table({
    head: ['File', 'Commits', 'Authors', 'Churn'].map(h => pc.dim(h)),
    colAligns: ['left', 'right', 'right', 'right'],
    style: { 'padding-left': 1, 'padding-right': 1, 'head': [], 'border': [] },
    chars: {
      'top': '',
      'top-mid': '',
      'top-left': '',
      'top-right': '',
      'bottom': '',
      'bottom-mid': '',
      'bottom-left': '',
      'bottom-right': '',
      'mid': '',
      'left-mid': '',
      'mid-mid': '',
      'right-mid': '',
      'left': ' ',
      'right': ' ',
      'middle': '  ',
    },
  })

  for (const s of stats) {
    const isHot = s.churnScore >= 0.7 && s.authorCount >= 3
    const file = isHot ? pc.yellow(s.filePath) : pc.cyan(s.filePath)
    const commits = String(s.commits)
    const authors = String(s.authorCount)
    const scoreVal = s.churnScore >= 0.7
      ? pc.red(String(s.churnScore))
      : s.churnScore >= 0.4
        ? pc.yellow(String(s.churnScore))
        : pc.green(String(s.churnScore))

    table.push([file, commits, authors, scoreVal])
  }

  out.push(table.toString())
  out.push('')
  return out.join('\n')
}

export function renderWhoKnows(
  filePath: string,
  totalLines: number,
  stats: { name: string, email: string, lines: number, commits: number, lastActive: number, score: number }[],
): string {
  const out: string[] = []

  out.push('')
  out.push(
    pc.bold(` Top experts for ${pc.cyan(filePath)}`)
    + pc.dim(` (${totalLines} lines, ${stats.length} author${stats.length !== 1 ? 's' : ''})`),
  )
  out.push('')

  const table = new Table({
    head: ['Rank', 'Author', 'Email', 'Lines', 'Commits', 'Last Active', 'Score'].map(h => pc.dim(h)),
    colAligns: ['right', 'left', 'left', 'right', 'right', 'left', 'right'],
    style: { 'padding-left': 1, 'padding-right': 1, 'head': [], 'border': [] },
    chars: {
      'top': '',
      'top-mid': '',
      'top-left': '',
      'top-right': '',
      'bottom': '',
      'bottom-mid': '',
      'bottom-left': '',
      'bottom-right': '',
      'mid': '',
      'left-mid': '',
      'mid-mid': '',
      'right-mid': '',
      'left': ' ',
      'right': ' ',
      'middle': '  ',
    },
  })

  for (const [i, s] of stats.entries()) {
    const rank = pc.bold(` ${i + 1}.`)
    const author = pc.cyan(s.name)
    const lines = pc.green(String(s.lines))
    const commits = String(s.commits)
    const lastActive = pc.dim(formatRelative(s.lastActive))
    const scoreVal = s.score >= 0.7 ? pc.green(String(s.score)) : s.score >= 0.4 ? pc.yellow(String(s.score)) : pc.dim(String(s.score))

    table.push([rank, author, pc.dim(s.email), lines, commits, lastActive, scoreVal])
  }

  out.push(table.toString())
  out.push('')
  return out.join('\n')
}

export function renderOnboarding(
  projectName: string,
  moduleOwners: { module: string, owner: string, score: number }[],
  churnStats: FileChurnStats[],
  staleFiles: StaleFile[],
  activity: ActivityStats,
  staleLabel: string,
): string {
  const date = new Date().toISOString().slice(0, 10)
  const out: string[] = []

  out.push(`# Project Knowledge Map — ${projectName}`)
  out.push('')
  out.push(`> Generated by blamewise on ${date}`)
  out.push('')

  // Module Owners
  out.push('## Module Owners')
  out.push('')
  out.push('| Module | Primary Owner | Score |')
  out.push('|--------|--------------|-------|')
  for (const m of moduleOwners) {
    out.push(`| ${m.module}/ | ${m.owner} | ${m.score} |`)
  }
  out.push('')

  // High Churn Files
  out.push('## High Churn Files')
  out.push('')
  for (const f of churnStats) {
    out.push(`- \`${f.filePath}\` — ${f.commits} commits, ${f.authorCount} authors`)
  }
  out.push('')

  // Stale Files
  if (staleFiles.length > 0) {
    out.push(`## Stale Files (no changes in ${staleLabel})`)
    out.push('')
    for (const f of staleFiles) {
      out.push(`- \`${f.filePath}\` — last changed by ${f.lastAuthor} (${f.lastDate})`)
    }
    out.push('')
  }

  // Activity Trend
  out.push('## Activity Trend')
  out.push('')
  out.push(`- Commits (30d): ${activity.commits30d}  |  Commits (60d): ${activity.commits60d}`)
  out.push(`- Active contributors (30d): ${activity.contributors30d}  |  Active contributors (60d): ${activity.contributors60d}`)
  out.push('')

  return out.join('\n')
}

export function renderWhy(
  filePath: string,
  entries: { sha: string, author: string, authorMail: string, date: string, subject: string }[],
): string {
  const out: string[] = []

  out.push('')
  out.push(pc.bold(` Recent changes to ${pc.cyan(filePath)}`))
  out.push('')

  for (const [i, e] of entries.entries()) {
    const short = e.sha.slice(0, 7)
    const dateObj = new Date(e.date)
    const rel = formatRelative(Math.floor(dateObj.getTime() / 1000))

    out.push(` ${pc.dim(`[${i + 1}]`)} ${pc.bold(e.subject)}`)
    out.push(`     ${pc.dim('Author:')} ${pc.cyan(e.author)} ${pc.dim(`<${e.authorMail}>`)}`)
    out.push(`     ${pc.dim('Date:')}   ${e.date.slice(0, 10)} ${pc.dim(`(${rel})`)}`)
    out.push(`     ${pc.dim('SHA:')}    ${pc.dim(short)}`)
    out.push('')
  }

  return out.join('\n')
}
